services:
  skanderbeg-gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: skanderbeg-gateway-dev
    environment:
      BASE_API_URL: ${BASE_API_URL:-http://skanderbeg.pm/api.php}
      API_PORT: ${API_PORT:-8000}
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./app:/app/app
      - cache_volume:/app/cache
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  cache_volume:
